### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by teyepe** [mfpiccolo/color_cat#1]
Hi, I'd like to use color_cat in my project, could you provide some short of instructions/example on how to use it?

**Comment by mfpiccolo** [comment]
There is an example in the test file that shows color_cat processing.

https://github.com/mfpiccolo/color_cat/blob/master/test/color_cat/process_test.rb

Basically you just call `ColorCat::Process.call` and pass it a url and it will return an array of hashes with information about the dominant colors of the images.  The first results are more dominant.

I have not ran the gem in some time so it may need a bit of gem dependency management to run in modern environments.
